module.exports = {
  coordinates: {
    originX: -32,
    originY: 32,
    unitWidth: 80,
    unitHeight: 80,
  },
  objects: {
    "card": {
      prototype: true,
      x: 0,
      y: 0,
      width: 1,
      height: 1.53333334,
      back: "dominion-space/card-back.jpg",
    },
    "acceleration": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/acceleration.jpg",
      x: 1,
      y: 0,
    },
    "acceleration-01": { prototypes: ["acceleration"] },
    "acceleration-02": { prototypes: ["acceleration"] },
    "acceleration-03": { prototypes: ["acceleration"] },
    "acceleration-04": { prototypes: ["acceleration"] },
    "acceleration-05": { prototypes: ["acceleration"] },
    "acceleration-06": { prototypes: ["acceleration"] },
    "acceleration-07": { prototypes: ["acceleration"] },
    "acceleration-08": { prototypes: ["acceleration"] },
    "acceleration-09": { prototypes: ["acceleration"] },
    "acceleration-10": { prototypes: ["acceleration"] },


    "air_lock": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/air_lock.jpg",
      x: 2,
      y: 0,
    },
    "air_lock-01": { prototypes: ["air_lock"] },
    "air_lock-02": { prototypes: ["air_lock"] },
    "air_lock-03": { prototypes: ["air_lock"] },
    "air_lock-04": { prototypes: ["air_lock"] },
    "air_lock-05": { prototypes: ["air_lock"] },
    "air_lock-06": { prototypes: ["air_lock"] },
    "air_lock-07": { prototypes: ["air_lock"] },
    "air_lock-08": { prototypes: ["air_lock"] },
    "air_lock-09": { prototypes: ["air_lock"] },
    "air_lock-10": { prototypes: ["air_lock"] },


    "asteroid": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/asteroid.jpg",
      x: 3,
      y: 0,
    },
    "asteroid-01": { prototypes: ["asteroid"] },
    "asteroid-02": { prototypes: ["asteroid"] },
    "asteroid-03": { prototypes: ["asteroid"] },
    "asteroid-04": { prototypes: ["asteroid"] },
    "asteroid-05": { prototypes: ["asteroid"] },
    "asteroid-06": { prototypes: ["asteroid"] },
    "asteroid-07": { prototypes: ["asteroid"] },
    "asteroid-08": { prototypes: ["asteroid"] },
    "asteroid-09": { prototypes: ["asteroid"] },
    "asteroid-10": { prototypes: ["asteroid"] },


    "auto_destruct": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/auto_destruct.jpg",
      x: 4,
      y: 0,
    },
    "auto_destruct-01": { prototypes: ["auto_destruct"] },
    "auto_destruct-02": { prototypes: ["auto_destruct"] },
    "auto_destruct-03": { prototypes: ["auto_destruct"] },
    "auto_destruct-04": { prototypes: ["auto_destruct"] },
    "auto_destruct-05": { prototypes: ["auto_destruct"] },
    "auto_destruct-06": { prototypes: ["auto_destruct"] },
    "auto_destruct-07": { prototypes: ["auto_destruct"] },
    "auto_destruct-08": { prototypes: ["auto_destruct"] },
    "auto_destruct-09": { prototypes: ["auto_destruct"] },
    "auto_destruct-10": { prototypes: ["auto_destruct"] },


    "biodome": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/biodome.jpg",
      x: 5,
      y: 0,
    },
    "biodome-01": { prototypes: ["biodome"] },
    "biodome-02": { prototypes: ["biodome"] },
    "biodome-03": { prototypes: ["biodome"] },
    "biodome-04": { prototypes: ["biodome"] },
    "biodome-05": { prototypes: ["biodome"] },
    "biodome-06": { prototypes: ["biodome"] },
    "biodome-07": { prototypes: ["biodome"] },
    "biodome-08": { prototypes: ["biodome"] },
    "biodome-09": { prototypes: ["biodome"] },
    "biodome-10": { prototypes: ["biodome"] },


    "black_hole": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/black_hole.jpg",
      x: 6,
      y: 0,
    },
    "black_hole-01": { prototypes: ["black_hole"] },
    "black_hole-02": { prototypes: ["black_hole"] },
    "black_hole-03": { prototypes: ["black_hole"] },
    "black_hole-04": { prototypes: ["black_hole"] },
    "black_hole-05": { prototypes: ["black_hole"] },
    "black_hole-06": { prototypes: ["black_hole"] },
    "black_hole-07": { prototypes: ["black_hole"] },
    "black_hole-08": { prototypes: ["black_hole"] },
    "black_hole-09": { prototypes: ["black_hole"] },
    "black_hole-10": { prototypes: ["black_hole"] },
    "black_hole-11": { prototypes: ["black_hole"] },
    "black_hole-12": { prototypes: ["black_hole"] },


    "bridge": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/bridge.jpg",
      x: 7,
      y: 0,
    },
    "bridge-01": { prototypes: ["bridge"] },
    "bridge-02": { prototypes: ["bridge"] },
    "bridge-03": { prototypes: ["bridge"] },
    "bridge-04": { prototypes: ["bridge"] },
    "bridge-05": { prototypes: ["bridge"] },
    "bridge-06": { prototypes: ["bridge"] },
    "bridge-07": { prototypes: ["bridge"] },
    "bridge-08": { prototypes: ["bridge"] },
    "bridge-09": { prototypes: ["bridge"] },
    "bridge-10": { prototypes: ["bridge"] },


    "comet": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/comet.jpg",
      x: 8,
      y: 0,
    },
    "comet-01": { prototypes: ["comet"] },
    "comet-02": { prototypes: ["comet"] },
    "comet-03": { prototypes: ["comet"] },
    "comet-04": { prototypes: ["comet"] },
    "comet-05": { prototypes: ["comet"] },
    "comet-06": { prototypes: ["comet"] },
    "comet-07": { prototypes: ["comet"] },
    "comet-08": { prototypes: ["comet"] },
    "comet-09": { prototypes: ["comet"] },
    "comet-10": { prototypes: ["comet"] },


    "communication": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/communication.jpg",
      x: 9,
      y: 0,
    },
    "communication-01": { prototypes: ["communication"] },
    "communication-02": { prototypes: ["communication"] },
    "communication-03": { prototypes: ["communication"] },
    "communication-04": { prototypes: ["communication"] },
    "communication-05": { prototypes: ["communication"] },
    "communication-06": { prototypes: ["communication"] },
    "communication-07": { prototypes: ["communication"] },
    "communication-08": { prototypes: ["communication"] },
    "communication-09": { prototypes: ["communication"] },
    "communication-10": { prototypes: ["communication"] },


    "computer": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/computer.jpg",
      x: 10,
      y: 0,
    },
    "computer-01": { prototypes: ["computer"] },
    "computer-02": { prototypes: ["computer"] },
    "computer-03": { prototypes: ["computer"] },
    "computer-04": { prototypes: ["computer"] },
    "computer-05": { prototypes: ["computer"] },
    "computer-06": { prototypes: ["computer"] },
    "computer-07": { prototypes: ["computer"] },
    "computer-08": { prototypes: ["computer"] },
    "computer-09": { prototypes: ["computer"] },
    "computer-10": { prototypes: ["computer"] },


    "copper": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/copper.jpg",
      x: 1,
      y: 1,
    },
    "copper-01": { prototypes: ["copper"] },
    "copper-02": { prototypes: ["copper"] },
    "copper-03": { prototypes: ["copper"] },
    "copper-04": { prototypes: ["copper"] },
    "copper-05": { prototypes: ["copper"] },
    "copper-06": { prototypes: ["copper"] },
    "copper-07": { prototypes: ["copper"] },
    "copper-08": { prototypes: ["copper"] },
    "copper-09": { prototypes: ["copper"] },
    "copper-10": { prototypes: ["copper"] },
    "copper-11": { prototypes: ["copper"] },
    "copper-12": { prototypes: ["copper"] },
    "copper-13": { prototypes: ["copper"] },
    "copper-14": { prototypes: ["copper"] },
    "copper-15": { prototypes: ["copper"] },
    "copper-16": { prototypes: ["copper"] },
    "copper-17": { prototypes: ["copper"] },
    "copper-18": { prototypes: ["copper"] },
    "copper-19": { prototypes: ["copper"] },
    "copper-20": { prototypes: ["copper"] },
    "copper-21": { prototypes: ["copper"] },
    "copper-22": { prototypes: ["copper"] },
    "copper-23": { prototypes: ["copper"] },
    "copper-24": { prototypes: ["copper"] },
    "copper-25": { prototypes: ["copper"] },
    "copper-26": { prototypes: ["copper"] },
    "copper-27": { prototypes: ["copper"] },
    "copper-28": { prototypes: ["copper"] },
    "copper-29": { prototypes: ["copper"] },
    "copper-30": { prototypes: ["copper"] },
    "copper-31": { prototypes: ["copper"] },
    "copper-32": { prototypes: ["copper"] },
    "copper-33": { prototypes: ["copper"] },
    "copper-34": { prototypes: ["copper"] },
    "copper-35": { prototypes: ["copper"] },
    "copper-36": { prototypes: ["copper"] },
    "copper-37": { prototypes: ["copper"] },
    "copper-38": { prototypes: ["copper"] },
    "copper-39": { prototypes: ["copper"] },
    "copper-40": { prototypes: ["copper"] },
    "copper-41": { prototypes: ["copper"] },
    "copper-42": { prototypes: ["copper"] },
    "copper-43": { prototypes: ["copper"] },
    "copper-44": { prototypes: ["copper"] },
    "copper-45": { prototypes: ["copper"] },
    "copper-46": { prototypes: ["copper"] },
    "copper-47": { prototypes: ["copper"] },
    "copper-48": { prototypes: ["copper"] },
    "copper-49": { prototypes: ["copper"] },
    "copper-50": { prototypes: ["copper"] },
    "copper-51": { prototypes: ["copper"] },
    "copper-52": { prototypes: ["copper"] },
    "copper-53": { prototypes: ["copper"] },
    "copper-54": { prototypes: ["copper"] },
    "copper-55": { prototypes: ["copper"] },
    "copper-56": { prototypes: ["copper"] },
    "copper-57": { prototypes: ["copper"] },
    "copper-58": { prototypes: ["copper"] },
    "copper-59": { prototypes: ["copper"] },
    "copper-60": { prototypes: ["copper"] },


    "curse": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/curse.jpg",
      x: 2,
      y: 1,
    },
    "curse-01": { prototypes: ["curse"] },
    "curse-02": { prototypes: ["curse"] },
    "curse-03": { prototypes: ["curse"] },
    "curse-04": { prototypes: ["curse"] },
    "curse-05": { prototypes: ["curse"] },
    "curse-06": { prototypes: ["curse"] },
    "curse-07": { prototypes: ["curse"] },
    "curse-08": { prototypes: ["curse"] },
    "curse-09": { prototypes: ["curse"] },
    "curse-10": { prototypes: ["curse"] },
    "curse-11": { prototypes: ["curse"] },
    "curse-12": { prototypes: ["curse"] },
    "curse-13": { prototypes: ["curse"] },
    "curse-14": { prototypes: ["curse"] },
    "curse-15": { prototypes: ["curse"] },
    "curse-16": { prototypes: ["curse"] },
    "curse-17": { prototypes: ["curse"] },
    "curse-18": { prototypes: ["curse"] },
    "curse-19": { prototypes: ["curse"] },
    "curse-20": { prototypes: ["curse"] },
    "curse-21": { prototypes: ["curse"] },
    "curse-22": { prototypes: ["curse"] },
    "curse-23": { prototypes: ["curse"] },
    "curse-24": { prototypes: ["curse"] },
    "curse-25": { prototypes: ["curse"] },
    "curse-26": { prototypes: ["curse"] },
    "curse-27": { prototypes: ["curse"] },
    "curse-28": { prototypes: ["curse"] },
    "curse-29": { prototypes: ["curse"] },
    "curse-30": { prototypes: ["curse"] },


    "duchy": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/duchy.jpg",
      x: 3,
      y: 1,
    },
    "duchy-01": { prototypes: ["duchy"] },
    "duchy-02": { prototypes: ["duchy"] },
    "duchy-03": { prototypes: ["duchy"] },
    "duchy-04": { prototypes: ["duchy"] },
    "duchy-05": { prototypes: ["duchy"] },
    "duchy-06": { prototypes: ["duchy"] },
    "duchy-07": { prototypes: ["duchy"] },
    "duchy-08": { prototypes: ["duchy"] },
    "duchy-09": { prototypes: ["duchy"] },
    "duchy-10": { prototypes: ["duchy"] },
    "duchy-11": { prototypes: ["duchy"] },
    "duchy-12": { prototypes: ["duchy"] },


    "engineer": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/engineer.jpg",
      x: 11,
      y: 0,
    },
    "engineer-01": { prototypes: ["engineer"] },
    "engineer-02": { prototypes: ["engineer"] },
    "engineer-03": { prototypes: ["engineer"] },
    "engineer-04": { prototypes: ["engineer"] },
    "engineer-05": { prototypes: ["engineer"] },
    "engineer-06": { prototypes: ["engineer"] },
    "engineer-07": { prototypes: ["engineer"] },
    "engineer-08": { prototypes: ["engineer"] },
    "engineer-09": { prototypes: ["engineer"] },
    "engineer-10": { prototypes: ["engineer"] },


    "ensign": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/ensign.jpg",
      x: 12,
      y: 0,
    },
    "ensign-01": { prototypes: ["ensign"] },
    "ensign-02": { prototypes: ["ensign"] },
    "ensign-03": { prototypes: ["ensign"] },
    "ensign-04": { prototypes: ["ensign"] },
    "ensign-05": { prototypes: ["ensign"] },
    "ensign-06": { prototypes: ["ensign"] },
    "ensign-07": { prototypes: ["ensign"] },
    "ensign-08": { prototypes: ["ensign"] },
    "ensign-09": { prototypes: ["ensign"] },
    "ensign-10": { prototypes: ["ensign"] },


    "estate": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/estate.jpg",
      x: 4,
      y: 1,
    },
    "estate-01": { prototypes: ["estate"] },
    "estate-02": { prototypes: ["estate"] },
    "estate-03": { prototypes: ["estate"] },
    "estate-04": { prototypes: ["estate"] },
    "estate-05": { prototypes: ["estate"] },
    "estate-06": { prototypes: ["estate"] },
    "estate-07": { prototypes: ["estate"] },
    "estate-08": { prototypes: ["estate"] },
    "estate-09": { prototypes: ["estate"] },
    "estate-10": { prototypes: ["estate"] },
    "estate-11": { prototypes: ["estate"] },
    "estate-12": { prototypes: ["estate"] },
    "estate-13": { prototypes: ["estate"] },
    "estate-14": { prototypes: ["estate"] },
    "estate-15": { prototypes: ["estate"] },
    "estate-16": { prototypes: ["estate"] },
    "estate-17": { prototypes: ["estate"] },
    "estate-18": { prototypes: ["estate"] },
    "estate-19": { prototypes: ["estate"] },
    "estate-20": { prototypes: ["estate"] },
    "estate-21": { prototypes: ["estate"] },
    "estate-22": { prototypes: ["estate"] },
    "estate-23": { prototypes: ["estate"] },
    "estate-24": { prototypes: ["estate"] },


    "force_field": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/force_field.jpg",
      x: 13,
      y: 0,
    },
    "force_field-01": { prototypes: ["force_field"] },
    "force_field-02": { prototypes: ["force_field"] },
    "force_field-03": { prototypes: ["force_field"] },
    "force_field-04": { prototypes: ["force_field"] },
    "force_field-05": { prototypes: ["force_field"] },
    "force_field-06": { prototypes: ["force_field"] },
    "force_field-07": { prototypes: ["force_field"] },
    "force_field-08": { prototypes: ["force_field"] },
    "force_field-09": { prototypes: ["force_field"] },
    "force_field-10": { prototypes: ["force_field"] },


    "galaxy": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/galaxy.jpg",
      x: 14,
      y: 0,
    },
    "galaxy-01": { prototypes: ["galaxy"] },
    "galaxy-02": { prototypes: ["galaxy"] },
    "galaxy-03": { prototypes: ["galaxy"] },
    "galaxy-04": { prototypes: ["galaxy"] },
    "galaxy-05": { prototypes: ["galaxy"] },
    "galaxy-06": { prototypes: ["galaxy"] },
    "galaxy-07": { prototypes: ["galaxy"] },
    "galaxy-08": { prototypes: ["galaxy"] },
    "galaxy-09": { prototypes: ["galaxy"] },
    "galaxy-10": { prototypes: ["galaxy"] },


    "gold": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/gold.jpg",
      x: 5,
      y: 1,
    },
    "gold-01": { prototypes: ["gold"] },
    "gold-02": { prototypes: ["gold"] },
    "gold-03": { prototypes: ["gold"] },
    "gold-04": { prototypes: ["gold"] },
    "gold-05": { prototypes: ["gold"] },
    "gold-06": { prototypes: ["gold"] },
    "gold-07": { prototypes: ["gold"] },
    "gold-08": { prototypes: ["gold"] },
    "gold-09": { prototypes: ["gold"] },
    "gold-10": { prototypes: ["gold"] },
    "gold-21": { prototypes: ["gold"] },
    "gold-22": { prototypes: ["gold"] },
    "gold-23": { prototypes: ["gold"] },
    "gold-24": { prototypes: ["gold"] },
    "gold-25": { prototypes: ["gold"] },
    "gold-26": { prototypes: ["gold"] },
    "gold-27": { prototypes: ["gold"] },
    "gold-28": { prototypes: ["gold"] },
    "gold-29": { prototypes: ["gold"] },
    "gold-30": { prototypes: ["gold"] },


    "gravity": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/gravity.jpg",
      x: 8,
      y: 1,
    },
    "gravity-01": { prototypes: ["gravity"] },
    "gravity-02": { prototypes: ["gravity"] },
    "gravity-03": { prototypes: ["gravity"] },
    "gravity-04": { prototypes: ["gravity"] },
    "gravity-05": { prototypes: ["gravity"] },
    "gravity-06": { prototypes: ["gravity"] },
    "gravity-07": { prototypes: ["gravity"] },
    "gravity-08": { prototypes: ["gravity"] },
    "gravity-09": { prototypes: ["gravity"] },
    "gravity-10": { prototypes: ["gravity"] },


    "gyroscope": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/gyroscope.jpg",
      x: 9,
      y: 1,
    },
    "gyroscope-01": { prototypes: ["gyroscope"] },
    "gyroscope-02": { prototypes: ["gyroscope"] },
    "gyroscope-03": { prototypes: ["gyroscope"] },
    "gyroscope-04": { prototypes: ["gyroscope"] },
    "gyroscope-05": { prototypes: ["gyroscope"] },
    "gyroscope-06": { prototypes: ["gyroscope"] },
    "gyroscope-07": { prototypes: ["gyroscope"] },
    "gyroscope-08": { prototypes: ["gyroscope"] },
    "gyroscope-09": { prototypes: ["gyroscope"] },
    "gyroscope-10": { prototypes: ["gyroscope"] },


    "landing": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/landing.jpg",
      x: 10,
      y: 1,
    },
    "landing-01": { prototypes: ["landing"] },
    "landing-02": { prototypes: ["landing"] },
    "landing-03": { prototypes: ["landing"] },
    "landing-04": { prototypes: ["landing"] },
    "landing-05": { prototypes: ["landing"] },
    "landing-06": { prototypes: ["landing"] },
    "landing-07": { prototypes: ["landing"] },
    "landing-08": { prototypes: ["landing"] },
    "landing-09": { prototypes: ["landing"] },
    "landing-10": { prototypes: ["landing"] },
    "landing-11": { prototypes: ["landing"] },
    "landing-12": { prototypes: ["landing"] },


    "laser": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/laser.jpg",
      x: 11,
      y: 1,
    },
    "laser-01": { prototypes: ["laser"] },
    "laser-02": { prototypes: ["laser"] },
    "laser-03": { prototypes: ["laser"] },
    "laser-04": { prototypes: ["laser"] },
    "laser-05": { prototypes: ["laser"] },
    "laser-06": { prototypes: ["laser"] },
    "laser-07": { prototypes: ["laser"] },
    "laser-08": { prototypes: ["laser"] },
    "laser-09": { prototypes: ["laser"] },
    "laser-10": { prototypes: ["laser"] },


    "light_speed": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/light_speed.jpg",
      x: 12,
      y: 1,
    },
    "light_speed-01": { prototypes: ["light_speed"] },
    "light_speed-02": { prototypes: ["light_speed"] },
    "light_speed-03": { prototypes: ["light_speed"] },
    "light_speed-04": { prototypes: ["light_speed"] },
    "light_speed-05": { prototypes: ["light_speed"] },
    "light_speed-06": { prototypes: ["light_speed"] },
    "light_speed-07": { prototypes: ["light_speed"] },
    "light_speed-08": { prototypes: ["light_speed"] },
    "light_speed-09": { prototypes: ["light_speed"] },
    "light_speed-10": { prototypes: ["light_speed"] },


    "mass": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/mass.jpg",
      x: 13,
      y: 1,
    },
    "mass-01": { prototypes: ["mass"] },
    "mass-02": { prototypes: ["mass"] },
    "mass-03": { prototypes: ["mass"] },
    "mass-04": { prototypes: ["mass"] },
    "mass-05": { prototypes: ["mass"] },
    "mass-06": { prototypes: ["mass"] },
    "mass-07": { prototypes: ["mass"] },
    "mass-08": { prototypes: ["mass"] },
    "mass-09": { prototypes: ["mass"] },
    "mass-10": { prototypes: ["mass"] },


    "oxygen": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/oxygen.jpg",
      x: 14,
      y: 1,
    },
    "oxygen-01": { prototypes: ["oxygen"] },
    "oxygen-02": { prototypes: ["oxygen"] },
    "oxygen-03": { prototypes: ["oxygen"] },
    "oxygen-04": { prototypes: ["oxygen"] },
    "oxygen-05": { prototypes: ["oxygen"] },
    "oxygen-06": { prototypes: ["oxygen"] },
    "oxygen-07": { prototypes: ["oxygen"] },
    "oxygen-08": { prototypes: ["oxygen"] },
    "oxygen-09": { prototypes: ["oxygen"] },
    "oxygen-10": { prototypes: ["oxygen"] },


    "photon_torpedoes": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/photon_torpedoes.jpg",
      x: 15,
      y: 1,
    },
    "photon_torpedoes-01": { prototypes: ["photon_torpedoes"] },
    "photon_torpedoes-02": { prototypes: ["photon_torpedoes"] },
    "photon_torpedoes-03": { prototypes: ["photon_torpedoes"] },
    "photon_torpedoes-04": { prototypes: ["photon_torpedoes"] },
    "photon_torpedoes-05": { prototypes: ["photon_torpedoes"] },
    "photon_torpedoes-06": { prototypes: ["photon_torpedoes"] },
    "photon_torpedoes-07": { prototypes: ["photon_torpedoes"] },
    "photon_torpedoes-08": { prototypes: ["photon_torpedoes"] },
    "photon_torpedoes-09": { prototypes: ["photon_torpedoes"] },
    "photon_torpedoes-10": { prototypes: ["photon_torpedoes"] },


    "planetary_rings": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/planetary_rings.jpg",
      x: 15,
      y: 0,
    },
    "planetary_rings-01": { prototypes: ["planetary_rings"] },
    "planetary_rings-02": { prototypes: ["planetary_rings"] },
    "planetary_rings-03": { prototypes: ["planetary_rings"] },
    "planetary_rings-04": { prototypes: ["planetary_rings"] },
    "planetary_rings-05": { prototypes: ["planetary_rings"] },
    "planetary_rings-06": { prototypes: ["planetary_rings"] },
    "planetary_rings-07": { prototypes: ["planetary_rings"] },
    "planetary_rings-08": { prototypes: ["planetary_rings"] },
    "planetary_rings-09": { prototypes: ["planetary_rings"] },
    "planetary_rings-10": { prototypes: ["planetary_rings"] },


    "province": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/province.jpg",
      x: 6,
      y: 1,
    },
    "province-01": { prototypes: ["province"] },
    "province-02": { prototypes: ["province"] },
    "province-03": { prototypes: ["province"] },
    "province-04": { prototypes: ["province"] },
    "province-05": { prototypes: ["province"] },
    "province-06": { prototypes: ["province"] },
    "province-07": { prototypes: ["province"] },
    "province-08": { prototypes: ["province"] },
    "province-09": { prototypes: ["province"] },
    "province-10": { prototypes: ["province"] },
    "province-11": { prototypes: ["province"] },
    "province-12": { prototypes: ["province"] },


    "refuel": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/refuel.jpg",
      x: 16,
      y: 0,
    },
    "refuel-01": { prototypes: ["refuel"] },
    "refuel-02": { prototypes: ["refuel"] },
    "refuel-03": { prototypes: ["refuel"] },
    "refuel-04": { prototypes: ["refuel"] },
    "refuel-05": { prototypes: ["refuel"] },
    "refuel-06": { prototypes: ["refuel"] },
    "refuel-07": { prototypes: ["refuel"] },
    "refuel-08": { prototypes: ["refuel"] },
    "refuel-09": { prototypes: ["refuel"] },
    "refuel-10": { prototypes: ["refuel"] },


    "robot": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/robot.jpg",
      x: 17,
      y: 0,
    },
    "robot-01": { prototypes: ["robot"] },
    "robot-02": { prototypes: ["robot"] },
    "robot-03": { prototypes: ["robot"] },
    "robot-04": { prototypes: ["robot"] },
    "robot-05": { prototypes: ["robot"] },
    "robot-06": { prototypes: ["robot"] },
    "robot-07": { prototypes: ["robot"] },
    "robot-08": { prototypes: ["robot"] },
    "robot-09": { prototypes: ["robot"] },
    "robot-10": { prototypes: ["robot"] },


    "shuttle": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/shuttle.jpg",
      x: 16,
      y: 1,
    },
    "shuttle-01": { prototypes: ["shuttle"] },
    "shuttle-02": { prototypes: ["shuttle"] },
    "shuttle-03": { prototypes: ["shuttle"] },
    "shuttle-04": { prototypes: ["shuttle"] },
    "shuttle-05": { prototypes: ["shuttle"] },
    "shuttle-06": { prototypes: ["shuttle"] },
    "shuttle-07": { prototypes: ["shuttle"] },
    "shuttle-08": { prototypes: ["shuttle"] },
    "shuttle-09": { prototypes: ["shuttle"] },
    "shuttle-10": { prototypes: ["shuttle"] },


    "sick_bay": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/sick_bay.jpg",
      x: 17,
      y: 1,
    },
    "sick_bay-01": { prototypes: ["sick_bay"] },
    "sick_bay-02": { prototypes: ["sick_bay"] },
    "sick_bay-03": { prototypes: ["sick_bay"] },
    "sick_bay-04": { prototypes: ["sick_bay"] },
    "sick_bay-05": { prototypes: ["sick_bay"] },
    "sick_bay-06": { prototypes: ["sick_bay"] },
    "sick_bay-07": { prototypes: ["sick_bay"] },
    "sick_bay-08": { prototypes: ["sick_bay"] },
    "sick_bay-09": { prototypes: ["sick_bay"] },
    "sick_bay-10": { prototypes: ["sick_bay"] },


    "silver": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/silver.jpg",
      x: 7,
      y: 1,
    },
    "silver-01": { prototypes: ["silver"] },
    "silver-02": { prototypes: ["silver"] },
    "silver-03": { prototypes: ["silver"] },
    "silver-04": { prototypes: ["silver"] },
    "silver-05": { prototypes: ["silver"] },
    "silver-06": { prototypes: ["silver"] },
    "silver-07": { prototypes: ["silver"] },
    "silver-08": { prototypes: ["silver"] },
    "silver-09": { prototypes: ["silver"] },
    "silver-10": { prototypes: ["silver"] },
    "silver-11": { prototypes: ["silver"] },
    "silver-12": { prototypes: ["silver"] },
    "silver-13": { prototypes: ["silver"] },
    "silver-14": { prototypes: ["silver"] },
    "silver-15": { prototypes: ["silver"] },
    "silver-16": { prototypes: ["silver"] },
    "silver-17": { prototypes: ["silver"] },
    "silver-18": { prototypes: ["silver"] },
    "silver-19": { prototypes: ["silver"] },
    "silver-20": { prototypes: ["silver"] },
    "silver-21": { prototypes: ["silver"] },
    "silver-22": { prototypes: ["silver"] },
    "silver-23": { prototypes: ["silver"] },
    "silver-24": { prototypes: ["silver"] },
    "silver-25": { prototypes: ["silver"] },
    "silver-26": { prototypes: ["silver"] },
    "silver-27": { prototypes: ["silver"] },
    "silver-28": { prototypes: ["silver"] },
    "silver-29": { prototypes: ["silver"] },
    "silver-30": { prototypes: ["silver"] },
    "silver-31": { prototypes: ["silver"] },
    "silver-32": { prototypes: ["silver"] },
    "silver-33": { prototypes: ["silver"] },
    "silver-34": { prototypes: ["silver"] },
    "silver-35": { prototypes: ["silver"] },
    "silver-36": { prototypes: ["silver"] },
    "silver-37": { prototypes: ["silver"] },
    "silver-38": { prototypes: ["silver"] },
    "silver-39": { prototypes: ["silver"] },
    "silver-40": { prototypes: ["silver"] },


    "space_ice": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/space_ice.jpg",
      x: 1,
      y: 2.7,
    },
    "space_ice-01": { prototypes: ["space_ice"] },
    "space_ice-02": { prototypes: ["space_ice"] },
    "space_ice-03": { prototypes: ["space_ice"] },
    "space_ice-04": { prototypes: ["space_ice"] },
    "space_ice-05": { prototypes: ["space_ice"] },
    "space_ice-06": { prototypes: ["space_ice"] },
    "space_ice-07": { prototypes: ["space_ice"] },
    "space_ice-08": { prototypes: ["space_ice"] },
    "space_ice-09": { prototypes: ["space_ice"] },
    "space_ice-10": { prototypes: ["space_ice"] },


    "space_junk": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/space_junk.jpg",
      x: 2,
      y: 2.7,
    },
    "space_junk-01": { prototypes: ["space_junk"] },
    "space_junk-02": { prototypes: ["space_junk"] },
    "space_junk-03": { prototypes: ["space_junk"] },
    "space_junk-04": { prototypes: ["space_junk"] },
    "space_junk-05": { prototypes: ["space_junk"] },
    "space_junk-06": { prototypes: ["space_junk"] },
    "space_junk-07": { prototypes: ["space_junk"] },
    "space_junk-08": { prototypes: ["space_junk"] },
    "space_junk-09": { prototypes: ["space_junk"] },
    "space_junk-10": { prototypes: ["space_junk"] },


    "space_rocks": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/space_rocks.jpg",
      x: 3,
      y: 2.7,
    },
    "space_rocks-01": { prototypes: ["space_rocks"] },
    "space_rocks-02": { prototypes: ["space_rocks"] },
    "space_rocks-03": { prototypes: ["space_rocks"] },
    "space_rocks-04": { prototypes: ["space_rocks"] },
    "space_rocks-05": { prototypes: ["space_rocks"] },
    "space_rocks-06": { prototypes: ["space_rocks"] },
    "space_rocks-07": { prototypes: ["space_rocks"] },
    "space_rocks-08": { prototypes: ["space_rocks"] },
    "space_rocks-09": { prototypes: ["space_rocks"] },
    "space_rocks-10": { prototypes: ["space_rocks"] },


    "space_station": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/space_station.jpg",
      x: 4,
      y: 2.7,
    },
    "space_station-01": { prototypes: ["space_station"] },
    "space_station-02": { prototypes: ["space_station"] },
    "space_station-03": { prototypes: ["space_station"] },
    "space_station-04": { prototypes: ["space_station"] },
    "space_station-05": { prototypes: ["space_station"] },
    "space_station-06": { prototypes: ["space_station"] },
    "space_station-07": { prototypes: ["space_station"] },
    "space_station-08": { prototypes: ["space_station"] },
    "space_station-09": { prototypes: ["space_station"] },
    "space_station-10": { prototypes: ["space_station"] },


    "space_suit": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/space_suit.jpg",
      x: 5,
      y: 2.7,
    },
    "space_suit-01": { prototypes: ["space_suit"] },
    "space_suit-02": { prototypes: ["space_suit"] },
    "space_suit-03": { prototypes: ["space_suit"] },
    "space_suit-04": { prototypes: ["space_suit"] },
    "space_suit-05": { prototypes: ["space_suit"] },
    "space_suit-06": { prototypes: ["space_suit"] },
    "space_suit-07": { prototypes: ["space_suit"] },
    "space_suit-08": { prototypes: ["space_suit"] },
    "space_suit-09": { prototypes: ["space_suit"] },
    "space_suit-10": { prototypes: ["space_suit"] },


    "sun": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/sun.jpg",
      x: 6,
      y: 2.7,
    },
    "sun-01": { prototypes: ["sun"] },
    "sun-02": { prototypes: ["sun"] },
    "sun-03": { prototypes: ["sun"] },
    "sun-04": { prototypes: ["sun"] },
    "sun-05": { prototypes: ["sun"] },
    "sun-06": { prototypes: ["sun"] },
    "sun-07": { prototypes: ["sun"] },
    "sun-08": { prototypes: ["sun"] },
    "sun-09": { prototypes: ["sun"] },
    "sun-10": { prototypes: ["sun"] },


    "super_nova": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/super_nova.jpg",
      x: 7,
      y: 2.7,
    },
    "super_nova-01": { prototypes: ["super_nova"] },
    "super_nova-02": { prototypes: ["super_nova"] },
    "super_nova-03": { prototypes: ["super_nova"] },
    "super_nova-04": { prototypes: ["super_nova"] },
    "super_nova-05": { prototypes: ["super_nova"] },
    "super_nova-06": { prototypes: ["super_nova"] },
    "super_nova-07": { prototypes: ["super_nova"] },
    "super_nova-08": { prototypes: ["super_nova"] },
    "super_nova-09": { prototypes: ["super_nova"] },
    "super_nova-10": { prototypes: ["super_nova"] },


    "thrusters": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/thrusters.jpg",
      x: 8,
      y: 2.7,
    },
    "thrusters-01": { prototypes: ["thrusters"] },
    "thrusters-02": { prototypes: ["thrusters"] },
    "thrusters-03": { prototypes: ["thrusters"] },
    "thrusters-04": { prototypes: ["thrusters"] },
    "thrusters-05": { prototypes: ["thrusters"] },
    "thrusters-06": { prototypes: ["thrusters"] },
    "thrusters-07": { prototypes: ["thrusters"] },
    "thrusters-08": { prototypes: ["thrusters"] },
    "thrusters-09": { prototypes: ["thrusters"] },
    "thrusters-10": { prototypes: ["thrusters"] },


    "unmanned_rocket": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/unmanned_rocket.jpg",
      x: 9,
      y: 2.7,
    },
    "unmanned_rocket-01": { prototypes: ["unmanned_rocket"] },
    "unmanned_rocket-02": { prototypes: ["unmanned_rocket"] },
    "unmanned_rocket-03": { prototypes: ["unmanned_rocket"] },
    "unmanned_rocket-04": { prototypes: ["unmanned_rocket"] },
    "unmanned_rocket-05": { prototypes: ["unmanned_rocket"] },
    "unmanned_rocket-06": { prototypes: ["unmanned_rocket"] },
    "unmanned_rocket-07": { prototypes: ["unmanned_rocket"] },
    "unmanned_rocket-08": { prototypes: ["unmanned_rocket"] },
    "unmanned_rocket-09": { prototypes: ["unmanned_rocket"] },
    "unmanned_rocket-10": { prototypes: ["unmanned_rocket"] },


    "vacuum": {
      prototype: true,
      prototypes: ["card"],
      front: "dominion-space/vacuum.jpg",
      x: 10,
      y: 2.7,
    },
    "vacuum-01": { prototypes: ["vacuum"] },
    "vacuum-02": { prototypes: ["vacuum"] },
    "vacuum-03": { prototypes: ["vacuum"] },
    "vacuum-04": { prototypes: ["vacuum"] },
    "vacuum-05": { prototypes: ["vacuum"] },
    "vacuum-06": { prototypes: ["vacuum"] },
    "vacuum-07": { prototypes: ["vacuum"] },
    "vacuum-08": { prototypes: ["vacuum"] },
    "vacuum-09": { prototypes: ["vacuum"] },
    "vacuum-10": { prototypes: ["vacuum"] },


    "die6": {
      prototype: true,
      width: 0.25,
      height: 0.25,
      faces: [
        "dice/d6_1.png",
        "dice/d6_2.png",
        "dice/d6_3.png",
        "dice/d6_4.png",
        "dice/d6_5.png",
        "dice/d6_6.png",
      ],
    },
    "d00": { prototypes: ["die6"], x: 0.50, y: 0},
    "d01": { prototypes: ["die6"], x: 0.50, y: 0.5},

  },
};
